### ISSUE TITLE
Check tests, update and re-release.

### ISSUE THREAD

**Issue by JJ** [perl6-community-modules/perl6-GD#6]
Including name change and stuff.

**Comment by jonathanstowe** [comment]
Having a look at the moment.  Except for the #4 I don't think there's anything majorly wrong with the code.

**Comment by jonathanstowe** [comment]
I'll probably have the core stuff done in the next day or two, I've added an `APIv2` label for those issues which may alter the current API.

**Comment by jonathanstowe** [comment]
Pushed the 8195eb3 which should address all the show-stopping issues.

**Comment by JJ** [comment]
Great job!

**Comment by jonathanstowe** [comment]
There's probably more work to be done with testing on various platforms (it may have a problem on FreeBSD for instance,) but they can be dealt with separately.

**Comment by JJ** [comment]
Thanks!
